name = "restaurant-gem"
type = "javascript"
main = "dist/server/index.js"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "bash build.sh"
cwd = "."

[env.production]
name = "restaurant-gem-prod"
routes = [
  { pattern = "restaurant-gem.pages.dev", zone_name = "pages.dev" }
]
